# install_nginx.yml
---
- name: Install and start Nginx
  hosts: web
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: true
